### ISSUE TITLE
Please add npm access

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.icons-freepic#1]
@jogibear9988 

This community adapter is not yet added to iobroker-community-adapters at npm.

Please grant access at npm to me so that I can add it to the iobroker-community-adapters organization at npm.
**Please execute "npm owner add mcm1957 iobroker.icons-freepic" at the commandline.**

Thanks in advance.
Please feel free to contact me if you have any questions.

**Comment by jogibear9988** [comment]
done
